# Generated by Django 6.0.4 on 2026-04-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_playerstat_team_playerstat_wickets_pointstableentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='batting_team',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='bowling_team',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='first_innings_overs',
            field=models.CharField(default='0.0', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='first_innings_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='first_innings_wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='innings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='target',
            field=models.IntegerField(default=0),
        ),
    ]
