# Generated by Django 6.0.4 on 2026-04-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_commentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='last_wicket_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='match',
            name='partnership_balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='partnership_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='player_of_match',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='player_of_match_figures',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='player_of_match_team',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
