# Generated by Django 6.0.4 on 2026-04-14 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_match_last_wicket_text_match_partnership_balls_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScorecardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings', models.IntegerField(default=1)),
                ('player_name', models.CharField(max_length=100)),
                ('team', models.CharField(blank=True, default='', max_length=100)),
                ('runs', models.IntegerField(default=0)),
                ('balls', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('strike_rate', models.FloatField(default=0)),
                ('wicket_info', models.CharField(blank=True, default='', max_length=255)),
                ('is_out', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.match')),
            ],
        ),
    ]
