# Generated by Django 6.0.4 on 2026-04-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_scorecardentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentplayers',
            name='non_striker',
            field=models.CharField(default='Non-Striker', max_length=100),
        ),
        migrations.AddField(
            model_name='currentplayers',
            name='non_striker_balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='currentplayers',
            name='non_striker_runs',
            field=models.IntegerField(default=0),
        ),
    ]
