# Generated by Django 6.0.4 on 2026-04-15 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_currentplayers_non_striker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('player_name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, default='', max_length=30)),
                ('is_playing_xi', models.BooleanField(default=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.match')),
            ],
        ),
    ]
