# Generated by Django 6.0.4 on 2026-04-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_teamplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecardentry',
            name='dismissal_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='scorecardentry',
            name='fielder_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
