# Generated by Django 6.0.4 on 2026-04-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_scorecardentry_dismissal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstat',
            name='economy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='fours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='sixes',
            field=models.IntegerField(default=0),
        ),
    ]
